name: build

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Android NDK
      run: sudo apt-get -y install android-sdk cmake ninja-build
    - name: Set up Android NDK
      env:
        ANDROID_NDK_VERSION: r27b
      run: |
        sudo mkdir -p /opt/android-sdk/ndk
        curl -sSL "https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip" -o android-ndk.zip
        sudo unzip android-ndk.zip -d /opt/android-sdk/ndk
        export ANDROID_NDK_HOME="/opt/android-sdk/ndk/android-ndk-${ANDROID_NDK_VERSION}"
        echo "ANDROID_NDK_HOME=${ANDROID_NDK_HOME}" >> $GITHUB_ENV
    - name: Configure for Android
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI=arm64-v8a \
              -DANDROID_PLATFORM=android-15 \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_C_FLAGS_RELEASE="-fdata-sections -ffunction-sections -Wl,--gc-sections" \
              -DCMAKE_EXE_LINKER_FLAGS="-Wl,-z,max-page-size=16384" \
              -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-z,max-page-size=16384" \
              -S . -B build-android -GNinja
    - name: Build for Android
      run: |
        cmake --build build-android --config Release
    - name: Archive Library and Headers
      run: |
        mkdir -p build-android/lib
        cp build-android/*.so build-android/lib/
        mkdir -p build-android/include
        cp -R include/* build-android/include/
        cd build-android && zip -r android-build.zip lib include
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-build
        path: build-android/android-build.zip
